name: Build and Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  
  build-test:
    runs-on: ubuntu-latest
    steps: 
      - name: '[Prep 1] Checkout'
        uses: actions/checkout@v3
        
      - name: '[prep 2] Install'
        run: |
          npm install